apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  containers:
    - image: lukondefmwila/dkr-multicontainer-app-client
      name: client
      ports:
        - containerPort: 3000
      resources: {}
  restartPolicy: OnFailure
status: {}
